// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfynpodlmpumkqdmkqaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeW5wb2RsbXB1bWtxZG1rcWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTc4MzIsImV4cCI6MjA2NTU3MzgzMn0.MCGxCqpl_ffqtW-wxBHlHT2YnFXEIrVw-owBmaIrOPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);